### PR TITLE
[WIP] Add HLL functions for Pastel Chime Continue C++

### PR DESCRIPTION
**Pull request by nao1215**
This PR contains the implementation for displaying the title screen of Pastel Chime Continue.
However, Pastel Chime Continue does not work with this PR due to lack of implementation.

I do not know what to implement in HLL function. Specifically, I don't even know where to get information on function arguments and return values. Where do you get HLL information from?

If you can tell me how to get the HLL information,  I will implement the rest of the codes related to this PR.

### CODE REVIEW

**Comment by nao1215** [comment]
I noticed that there is a library file in the DLL directory. I check the contents of this library.

**Comment by kichikuou** [comment]
You can use [alice-tools](https://github.com/nunuhara/alice-tools) to dump HLL information. For example:
```sh
alice ain dump -l ぱすてる２.ain
```

Note that this dumps function signatures in the System4 language. It's not always obvious how System4 types are mapped to C types in xsystem4.

I have a patch to alice-tools which adds an option to generate HLL stubs for xsystem4. (Probably @nunuhara also have something similar to this.) I'll rebase it and create a PR when I have time. https://github.com/kichikuou/alice-tools/commit/f37162c390a5398df6a397890400d3a392378831


Actually, I have attempted to support Pastel Chime 2 in the past but gave up because random dungeon generation was done in native code in a HLL (`PastelChime2.AutoDungeonE_Create`). In order to reproduce the gameplay faithfully, we will have to reverse engineer the HLL's code.

**Comment by kichikuou** [comment]
Here's my old attempt, if you are interested: https://github.com/kichikuou/xsystem4/tree/pascha2

**Comment by nao1215** [comment]
@kichikuou 
Thanks for the detailed information.
I will proceed with the implementation based on the information you provided.

>Actually, I have attempted to support Pastel Chime 2 in the past but gave up because random dungeon generation was done in native code in a HLL (PastelChime2.AutoDungeonE_Create). In order to reproduce the gameplay faithfully, we will have to reverse engineer the HLL's code.

I read this comment and thought, "Not easy fix!!".

**Comment by nao1215** [comment]
@kichikuou 
I have a question.
How did you implement [DrawNumeral HALL](https://github.com/nunuhara/xsystem4/commit/9335a5b483b34d6f0cacd4a5c0336024f6a3a38e)?

For example, did you disassemble DrawNumeral.dll with a tool like Ghidra and write C code from the contents of the assembler? Did you use a different way?

**Comment by kichikuou** [comment]
I did not disassemble DrawNumeral.dll.

In most cases, it's possible to guess what the function does from the function name, its parameter names, and how the function is called (reading decompiled AIN code). If you're not sure how the function behaves in corner cases, change the AIN code and experiment. (AinDecompiler is your friend.)

As for DrawNumeral, I could guess that it was meant to create a "magic sprite" that automatically displays a number in the format specified by DrawNumeral.Register. Then I wrote the code to achieve that functionality.

This is why I said it is difficult to reproduce the dungeon generation code. There are infinite number of ways to generate a dungeon map, and the algorithm cannot be determined only from the function interface.

**Comment by nao1215** [comment]
@kichikuou 
Thank you for your reply.

>I did not disassemble DrawNumeral.dll.

Now, I know why your code and disassembled results don't match.

>In most cases, it's possible to guess what the function does from the function name, its parameter names, and how the function is called (reading decompiled AIN code). If you're not sure how the function behaves in corner cases, change the AIN code and experiment. (AinDecompiler is your friend.)

I had not checked the AIN code. This is useful information.

>This is why I said it is difficult to reproduce the dungeon generation code. There are infinite number of ways to generate a dungeon map, and the algorithm cannot be determined only from the function interface.

I am also not used to reverse engineering DLLs, so I may give up that implement  the dungeon generation code.  
However, there is a possibility to implement HLL for Pastel Chime C++. I'll try some more.

**Comment by nao1215** [comment]
[Status of implementation]
Now,  "Pastel Chime Q++" does not work. Out of memory error occur. 
The error log is shown below.
```
クイズ／編入試験０１
*WARNING*(../src/hll/PastelChime2.c:PastelChime2_DungeonDataToSaveData:31): Unimplemented HLL function: PastelChime2.DungeonDataToSaveData
ResumeSave(ぱすちゃ＋v.1.00,ぱすちゃ＋AUTO.ASD)成功
*WARNING*(../src/hll/PastelChime2.c:PastelChime2_DungeonDataFromSaveData:32): Unimplemented HLL function: PastelChime2.DungeonDataFromSaveData
*ERROR*(file_read): Out of memory
```

Other than that, it appears to be working well.

**Comment by nunuhara** [comment]
The out of memory error seems to be caused by `ACXLoaderP2_Load` calling `acx_read` on a directory. I've added a check in `file_read` in libsys4 to catch this error, but the fact that `ACXLoaderP2_Load` is getting a directory path as an argument likely indicates there's a bug elsewhere.

**Comment by nao1215** [comment]
I will send out another PR after I complete the implementation.

**Pull request closed without merging**
